NDefines.NGame.START_DATE = "1929.1.1.12"
NDefines.NGame.END_DATE = "1960.1.1.12"
NDefines.NGame.MAX_SCRIPTED_LOC_RECURSION = 60 -- 30

NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 25
NDefines.NBuildings.MAX_BUILDING_LEVELS = 500